[package]
name = "dhlog"
version = "0.1.0"
edition = "2024"

[dependencies]
dirs = "6.0.0"
lazy_static = "1.5.0"
libc = "0.2.175"
memmap2 = "0.9.8"
notify = "8.2.0"
once_cell = "1.21.3"
regex = "1.11.2"
